version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo $CIRCLE_BRANCH
            echo $HEAD_BRANCH
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "On the main branch. Running the deployment script..."
            else
              echo "Not on the main branch. Skipping deployment."
            fi
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
