version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo $CIRCLE_BRANCH
            echo $HEAD_BRANCH
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "On the main branch. Running the deployment script..."
            else
              echo "Not on the main branch. Skipping deployment."
            fi
      - run:
          name: "Install endorctl"
          command: |
            curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
            echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
            if [ $? -ne 0 ]; then
              echo "Integrity check failed";
              exit 1;
            fi
            chmod +x ./endorctl
            ./endorctl --version            
      - run:
          name: "Endor Labs Test"
          command: |
            ./endorctl scan --dependencies --secrets     
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
